<Project>
  <PropertyGroup>
    <BaseIntermediateOutputPath>$(MSBuildProjectDirectory)\..\..\reports\configurator\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <BaseOutputPath>$(MSBuildProjectDirectory)\..\..\reports\configurator\bin\$(MSBuildProjectName)\</BaseOutputPath>
  </PropertyGroup>
</Project>
